// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj-edXJq_Hz5qFbghhvkZTq2rcgIJQ-AI',
    appId: '1:731202696493:android:9249ca9aa791ffef13cfa4',
    messagingSenderId: '731202696493',
    projectId: 'fpv-drohne',
    databaseURL: 'https://fpv-drohne-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fpv-drohne.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyrAdR8AWFJzxlDE59Qr2Xo4h_2x-lZVQ',
    appId: '1:731202696493:ios:be87663332d94f1413cfa4',
    messagingSenderId: '731202696493',
    projectId: 'fpv-drohne',
    databaseURL: 'https://fpv-drohne-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fpv-drohne.appspot.com',
    iosClientId: '731202696493-4gq05ea52jj8uf8vmn715ug1tvjtig7h.apps.googleusercontent.com',
    iosBundleId: 'com.example.drone20',
  );
}
